In [17]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/final-datathon/Datathon_TrainData_org.csv


In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [18]:
df=pd.read_csv("/kaggle/input/final-datathon/Datathon_TrainData_org.csv")
df

Country              Date          Speaker  \
0             Russia        24-01-2000   Vladimir Putin   
1                USA  09-09-2021 00:00        Joe Biden   
2             Russia        24-12-2004   Vladimir Putin   
3                USA        14-08-2014     Barack Obama   
4                USA  26-03-2021 00:00        Joe Biden   
...              ...               ...              ...   
1612  United Kingdom         24-Jul-19    Boris Johnson   
1613             USA  01-02-2021 00:00        Joe Biden   
1614             USA        30-09-2015     Barack Obama   
1615           China  23-06-2021 00:00     H.E. Wang Yi   
1616           China  06-06-2016 00:00  H.E. Xi Jinping   

                                               Headline  \
0     Speech at a conference of the heads of republi...   
1     Remarks by President Biden on Fighting the COV...   
2     Excerpts from the Opening Speech at a Session ...   
3                          \nStatement by the President   
4     Statement by President Biden on the Attack on ...   
...                                                 ...   
1612  Boris Johnson's first speech as Prime Minister...   
1613  Statement by President Joe Biden On Black Hist...   
1614  \nRemarks by the President Meeting with State ...   
1615  Let Us Strengthen Confidence and Solidarity an...   
1616  Making Unremitting Efforts for a New Model of ...   

                                         Text_of_Speech  \
0     Esteemed Mr Lebedev,\n\nLadies and Gentlemen:\...   
1     THE PRESIDENT:  Good evening, my fellow Americ...   
2     Good afternoon, dear colleagues,\n\nOur meetin...   
3     Good afternoon, everybody. This sound system i...   
4     More Americans voted in the 2020 elections tha...   
...                                                 ...   
1612  Good afternoon I have just been to see Her Maj...   
1613  This February, during Black History Month, I c...   
1614  Thank you so much.  Everybody have a seat.  We...   
1615  Colleagues,\nFriends,\n\nIn 2013, President Xi...   
1616  Secretary of State John Kerry,\nSecretary of t...   

                                            Designation Running President/PM  \
0                                             President       Vladimir Putin   
1                                             President            Joe Biden   
2                                             President       Vladimir Putin   
3                                             President         Barack Obama   
4                                             President            Joe Biden   
...                                                 ...                  ...   
1612                                     Prime Minister        Boris Johnson   
1613                                          President            Joe Biden   
1614                                          President         Barack Obama   
1615  State Councilor and Foreign Minister of the Pe...           Xi Jinping   
1616                                          President           Xi Jinping   

                                            Speech Link   Emotion  \
0     http://en.kremlin.ru/events/president/transcri...     UPSET   
1     https://www.whitehouse.gov/briefing-room/speec...  OPTIMISM   
2     http://en.kremlin.ru/events/president/transcri...   NEUTRAL   
3     https://obamawhitehouse.archives.gov/the-press...   NEUTRAL   
4     https://www.whitehouse.gov/briefing-room/speec...     UPSET   
...                                                 ...       ...   
1612  https://www.gov.uk/government/speeches/boris-j...  OPTIMISM   
1613  https://www.whitehouse.gov/briefing-room/state...  OPTIMISM   
1614  https://obamawhitehouse.archives.gov/the-press...   NEUTRAL   
1615  https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/z...       JOY   
1616  https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/z...  OPTIMISM   

                    Context  
0                    OTHERS  
1               DEVELOPMENT  
2     

In [22]:
df.isnull().sum()

Country                 0
Date                    0
Speaker                 0
Headline                0
Text_of_Speech          0
Designation             0
Running President/PM    0
Speech Link             0
Emotion                 0
Context                 0
dtype: int64

In [25]:
df = df.dropna()

In [27]:
df['Text_of_Speech'].fillna('', inplace=True)

In [28]:
X = df['Text_of_Speech']
y = df['Emotion']

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
tfidf_vectorizer = TfidfVectorizer(max_features=1000, stop_words='english')
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [36]:
def finalfunction(model):
    model =model
    model.fit(X_train_tfidf, y_train)
    y_pred = model.predict(X_test_tfidf)
    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    confusion = confusion_matrix(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    # Print the evaluation metrics
    print("Accuracy:", accuracy)
    print("\nConfusion Matrix:\n", confusion)
    print("\nClassification Report:\n", classification_rep)

In [38]:
model = LogisticRegression()
finalfunction(model)

Accuracy: 0.48598130841121495

Confusion Matrix:
 [[47 13 16  2]
 [16 45 31  3]
 [11 34 45  2]
 [13 19  5 19]]

Classification Report:
               precision    recall  f1-score   support

         JOY       0.54      0.60      0.57        78
     NEUTRAL       0.41      0.47      0.44        95
    OPTIMISM       0.46      0.49      0.48        92
       UPSET       0.73      0.34      0.46        56

    accuracy                           0.49       321
   macro avg       0.54      0.48      0.49       321
weighted avg       0.51      0.49      0.49       321



In [40]:
from catboost import CatBoostClassifier

In [41]:
model=CatBoostClassifier()
finalfunction(model)

Learning rate set to 0.080142
0:	learn: 1.3736029	total: 919ms	remaining: 15m 17s
1:	learn: 1.3622896	total: 1.49s	remaining: 12m 23s
2:	learn: 1.3517658	total: 1.99s	remaining: 11m
3:	learn: 1.3402863	total: 2.49s	remaining: 10m 19s
4:	learn: 1.3279096	total: 2.98s	remaining: 9m 53s
5:	learn: 1.3201545	total: 3.48s	remaining: 9m 36s
6:	learn: 1.3112246	total: 3.99s	remaining: 9m 25s
7:	learn: 1.3003216	total: 4.49s	remaining: 9m 16s
8:	learn: 1.2913565	total: 4.99s	remaining: 9m 9s
9:	learn: 1.2847692	total: 5.48s	remaining: 9m 2s
10:	learn: 1.2772113	total: 6.26s	remaining: 9m 22s
11:	learn: 1.2702702	total: 7.18s	remaining: 9m 51s
12:	learn: 1.2639488	total: 7.76s	remaining: 9m 49s
13:	learn: 1.2546778	total: 8.26s	remaining: 9m 41s
14:	learn: 1.2461796	total: 8.75s	remaining: 9m 34s
15:	learn: 1.2395885	total: 9.24s	remaining: 9m 28s
16:	learn: 1.2336544	total: 9.73s	remaining: 9m 22s
17:	learn: 1.2275943	total: 10.2s	remaining: 9m 17s
18:	learn: 1.2231221	total: 10.7s	remaining: 9